### ISSUE TITLE
When I just use serviceImport across the cluster, I cannot access the server

### ISSUE THREAD

**Issue by zishen** [coredns/multicluster#15]
I deploy a server foo in member1, and use serviceImport to import this foo in another k8s cluster named member2.
Member2 donnot has foo or it's endpointSlice. But I cannot access "foo.default.svc.cluster.local" in member2, but ok in member1.

I've already done something:

1).Config the coredns corefile:

.:53 {
    multicluster cluster.local.
}

2). Build and install the multicluster as 

...
kubernetes:kubernetes
multicluster:github.com/coredns/multicluster
...

in plugin.cfg

3). Add the RBAC

```tex
- apiGroups:
  - multicluster.x-k8s.io
  resources:
  - serviceimports
  verbs:
  - list
  - watch
```

4). The serviceImport.yaml is :

```yaml
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: foo
  namespace: default
spec:
  type: ClusterSetIP
  ports:
  - name: foo
    port: 80
    protocol: TCP
  ips:
  - "10.10.0.5"
```

version: k8s:1.21,coredns:v1.9.3 and above version

So, what's wrong with this?
